/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TableImport } from './routes/table'

// Create Virtual Routes

const QueryLazyImport = createFileRoute('/query')()
const InfiniteLazyImport = createFileRoute('/infinite')()
const FormLazyImport = createFileRoute('/form')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const QueryLazyRoute = QueryLazyImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/query.lazy').then((d) => d.Route))

const InfiniteLazyRoute = InfiniteLazyImport.update({
  id: '/infinite',
  path: '/infinite',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/infinite.lazy').then((d) => d.Route))

const FormLazyRoute = FormLazyImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const TableRoute = TableImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/infinite': {
      id: '/infinite'
      path: '/infinite'
      fullPath: '/infinite'
      preLoaderRoute: typeof InfiniteLazyImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/table': typeof TableRoute
  '/form': typeof FormLazyRoute
<<<<<<< HEAD
=======
  '/infinite': typeof InfiniteLazyRoute
>>>>>>> 7c95042 (update)
  '/query': typeof QueryLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/table': typeof TableRoute
  '/form': typeof FormLazyRoute
<<<<<<< HEAD
=======
  '/infinite': typeof InfiniteLazyRoute
>>>>>>> 7c95042 (update)
  '/query': typeof QueryLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/table': typeof TableRoute
  '/form': typeof FormLazyRoute
<<<<<<< HEAD
=======
  '/infinite': typeof InfiniteLazyRoute
>>>>>>> 7c95042 (update)
  '/query': typeof QueryLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths: '/' | '/table' | '/form' | '/query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/table' | '/form' | '/query'
  id: '__root__' | '/' | '/table' | '/form' | '/query'
=======
  fullPaths: '/' | '/table' | '/form' | '/infinite' | '/query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/table' | '/form' | '/infinite' | '/query'
  id: '__root__' | '/' | '/table' | '/form' | '/infinite' | '/query'
>>>>>>> 7c95042 (update)
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TableRoute: typeof TableRoute
  FormLazyRoute: typeof FormLazyRoute
<<<<<<< HEAD
=======
  InfiniteLazyRoute: typeof InfiniteLazyRoute
>>>>>>> 7c95042 (update)
  QueryLazyRoute: typeof QueryLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TableRoute: TableRoute,
  FormLazyRoute: FormLazyRoute,
<<<<<<< HEAD
=======
  InfiniteLazyRoute: InfiniteLazyRoute,
>>>>>>> 7c95042 (update)
  QueryLazyRoute: QueryLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/table",
        "/form",
<<<<<<< HEAD
=======
        "/infinite",
>>>>>>> 7c95042 (update)
        "/query"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/table": {
      "filePath": "table.tsx"
    },
    "/form": {
      "filePath": "form.lazy.tsx"
    },
<<<<<<< HEAD
=======
    "/infinite": {
      "filePath": "infinite.lazy.tsx"
    },
>>>>>>> 7c95042 (update)
    "/query": {
      "filePath": "query.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
